package First.impl;

import First.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultInnerLayer <br>
 * @version generated on Wed Nov 16 17:10:01 IST 2016 by Sai
 */
public class DefaultInnerLayer extends WrappedIndividualImpl implements InnerLayer {

    public DefaultInnerLayer(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Components
     */
     
    public Collection<? extends InnerLayer> getComponents() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_COMPONENTS,
                                               DefaultInnerLayer.class);
    }

    public boolean hasComponents() {
	   return !getComponents().isEmpty();
    }

    public void addComponents(InnerLayer newComponents) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_COMPONENTS,
                                       newComponents);
    }

    public void removeComponents(InnerLayer oldComponents) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_COMPONENTS,
                                          oldComponents);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Contains
     */
     
    public Collection<? extends Content> getContains() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CONTAINS,
                                               DefaultContent.class);
    }

    public boolean hasContains() {
	   return !getContains().isEmpty();
    }

    public void addContains(Content newContains) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CONTAINS,
                                       newContains);
    }

    public void removeContains(Content oldContains) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CONTAINS,
                                          oldContains);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#FeelLike
     */
     
    public Collection<? extends OuterLayer> getFeelLike() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_FEELLIKE,
                                               DefaultOuterLayer.class);
    }

    public boolean hasFeelLike() {
	   return !getFeelLike().isEmpty();
    }

    public void addFeelLike(OuterLayer newFeelLike) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_FEELLIKE,
                                       newFeelLike);
    }

    public void removeFeelLike(OuterLayer oldFeelLike) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_FEELLIKE,
                                          oldFeelLike);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#LooksLikeInside
     */
     
    public Collection<? extends Colour> getLooksLikeInside() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_LOOKSLIKEINSIDE,
                                               DefaultColour.class);
    }

    public boolean hasLooksLikeInside() {
	   return !getLooksLikeInside().isEmpty();
    }

    public void addLooksLikeInside(Colour newLooksLikeInside) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_LOOKSLIKEINSIDE,
                                       newLooksLikeInside);
    }

    public void removeLooksLikeInside(Colour oldLooksLikeInside) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_LOOKSLIKEINSIDE,
                                          oldLooksLikeInside);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#LooksLikeOutside
     */
     
    public Collection<? extends Colour> getLooksLikeOutside() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_LOOKSLIKEOUTSIDE,
                                               DefaultColour.class);
    }

    public boolean hasLooksLikeOutside() {
	   return !getLooksLikeOutside().isEmpty();
    }

    public void addLooksLikeOutside(Colour newLooksLikeOutside) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_LOOKSLIKEOUTSIDE,
                                       newLooksLikeOutside);
    }

    public void removeLooksLikeOutside(Colour oldLooksLikeOutside) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_LOOKSLIKEOUTSIDE,
                                          oldLooksLikeOutside);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#FruitName
     */
     
    public Collection<? extends String> getFruitName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FRUITNAME, String.class);
    }

    public boolean hasFruitName() {
		return !getFruitName().isEmpty();
    }

    public void addFruitName(String newFruitName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FRUITNAME, newFruitName);
    }

    public void removeFruitName(String oldFruitName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FRUITNAME, oldFruitName);
    }


}
