package First;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Nov 16 17:10:01 IST 2016 by Sai
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Colour
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COLOUR.<p>
     * 
     */
    public static final OWLClass CLASS_COLOUR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Colour"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Content
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Content"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Crunchy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CRUNCHY.<p>
     * 
     */
    public static final OWLClass CLASS_CRUNCHY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Crunchy"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Edible
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EDIBLE.<p>
     * 
     */
    public static final OWLClass CLASS_EDIBLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Edible"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Fruits
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FRUITS.<p>
     * 
     */
    public static final OWLClass CLASS_FRUITS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Fruits"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#InnerLayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INNERLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_INNERLAYER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#InnerLayer"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#NotEdible
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOTEDIBLE.<p>
     * 
     */
    public static final OWLClass CLASS_NOTEDIBLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#NotEdible"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#NotPresent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOTPRESENT.<p>
     * 
     */
    public static final OWLClass CLASS_NOTPRESENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#NotPresent"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#OuterLayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OUTERLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_OUTERLAYER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#OuterLayer"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Present
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRESENT.<p>
     * 
     */
    public static final OWLClass CLASS_PRESENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Present"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Prickly
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRICKLY.<p>
     * 
     */
    public static final OWLClass CLASS_PRICKLY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Prickly"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Ribbed
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RIBBED.<p>
     * 
     */
    public static final OWLClass CLASS_RIBBED = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Ribbed"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Seeds
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEEDS.<p>
     * 
     */
    public static final OWLClass CLASS_SEEDS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Seeds"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Smooth
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SMOOTH.<p>
     * 
     */
    public static final OWLClass CLASS_SMOOTH = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Smooth"));

    /* ***************************************************
     * Class http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Soft
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SOFT.<p>
     * 
     */
    public static final OWLClass CLASS_SOFT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Soft"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Components
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPONENTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPONENTS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Components"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Contains"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#FeelLike
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FEELLIKE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FEELLIKE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#FeelLike"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#LooksLikeInside
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOOKSLIKEINSIDE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOOKSLIKEINSIDE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#LooksLikeInside"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#LooksLikeOutside
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOOKSLIKEOUTSIDE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOOKSLIKEOUTSIDE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#LooksLikeOutside"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Carbohydrate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CARBOHYDRATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CARBOHYDRATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Carbohydrate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Cholestrol
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHOLESTROL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHOLESTROL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Cholestrol"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#ColourName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLOURNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLOURNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#ColourName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Fat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FAT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FAT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Fat"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#FruitName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FRUITNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FRUITNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#FruitName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Potassium
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POTASSIUM.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POTASSIUM = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Potassium"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Protiens
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROTIENS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROTIENS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Protiens"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Sodium
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SODIUM.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SODIUM = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/mahe/ontologies/2016/9/untitled-ontology-8#Sodium"));


}
